#!/bin/sh
set -eu

# Replace the binary inside the stable app bundle from a verified release
# artifact. The manifest is generated by build-pkg.sh and contains a URL and
# sha256; an empty URL intentionally makes update fail closed.
RESOURCES="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
APP="$(CDPATH= cd -- "$RESOURCES/../.." && pwd)"
BIN="$APP/Contents/MacOS/macbotd"
MANIFEST="$RESOURCES/update-manifest.json"
URL="$(/usr/bin/plutil -extract url raw -o - "$MANIFEST" 2>/dev/null || true)"
SHA256="$(/usr/bin/plutil -extract sha256 raw -o - "$MANIFEST" 2>/dev/null || true)"
if [ -z "$URL" ] || [ "$URL" = "null" ]; then
  echo "no update URL configured in $MANIFEST" >&2
  exit 2
fi
if [ ${#SHA256} -ne 64 ]; then
  echo "no valid update checksum configured in $MANIFEST" >&2
  exit 2
fi
case "$SHA256" in *[!0-9a-fA-F]*) echo "invalid update checksum" >&2; exit 2 ;; esac
TMP="$(mktemp "${TMPDIR:-/tmp}/macbot-update.XXXXXX")"
trap 'rm -f "$TMP"' EXIT INT TERM
/usr/bin/curl --fail --location --silent --show-error "$URL" -o "$TMP"
ACTUAL="$(/usr/bin/shasum -a 256 "$TMP" | awk '{print $1}')"
[ "$ACTUAL" = "$SHA256" ] || { echo "update checksum mismatch" >&2; exit 3; }
chmod 755 "$TMP"
VERSION="$("$TMP" --version)"
case "$VERSION" in macbotd\ *) ;; *) echo "invalid daemon release artifact" >&2; exit 4 ;; esac
install -m 755 "$TMP" "$BIN.new"
mv -f "$BIN.new" "$BIN"
CONSOLE_UID="$(id -u)"
/bin/launchctl kickstart -k "gui/$CONSOLE_UID/${MACBOT_LAUNCH_LABEL:-com.macbot.server}" 2>/dev/null || true
echo "updated $BIN"
